<?php
/**
 * Copyright (c) 2024 Attila Sagi
 * @license http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper \Magento\Framework\Escaper
 * @var $viewModel \Space\ProductPurchaseCount\ViewModel\Catalog\View\Count
 */

$viewModel = $block->getData('view_model');
?>
<?php if (null !== $viewModel): ?>
    <p><?= $escaper->escapeHtml($viewModel->getOrdersCount()) ?></p>
<?php endif; ?>
